# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='標題')),
                ('content', models.TextField(verbose_name='大概')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='發表時間')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間')),
            ],
        ),
    ]
